spring.application.name=backend


# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5434/cand_db?currentSchema=public&allowEncodingChanges=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.datasource.username=user
spring.datasource.password=cand123@


# POSTGRESQL DB + DATA JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# SECURITY
jwt.secret=YXNqZGlvYWpzZmlqYWlzb2Zqc29pYXBwY2FuZGFzamRvaWFzamRpb2FzamRvaWFzamRvaWFqb2FwcGNhZGFzaW9kanNhaW9kamFzaW8=
jwt.expiration=604800000

# MAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hohoanglong2508@gmail.com
spring.mail.password=wagu qgsx ogck exml
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# SWAGGER UI
springdoc.swagger-ui.path=/docs